server:
  port: 20009
spring:
  datasource:
    url: jdbc:mysql://mysql-server:3306/cloud?useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  redis:
    # Redis默认是16个数据库，可以通过配置文件进行修改。
    # 每个数据库都有一个index来访问，没有名称！
    # 默认情况下，database的值是0~15。
    database: 0
    host: 127.0.0.1
    port: 6379
    # 基于哨兵的方式连接，需要指定master的id和所有的哨兵
#    sentinel:
#      master: master1
#      nodes: 192.168.43.19:26379,192.168.43.19:26380,192.168.43.19:26381
    # 基于集群方式的访问
#    cluster:
#      nodes: 192.168.9.101:6379,192.168.9.102:6379,192.168.9.103:6379
