fk:
  host-prefix: http://127.0.0.1:8080
  api-path: /api
  api-prefix: ${fk.host-prefix}${fk.api-path}
logging:
  level:
    root: ERROR
    org:
      fkjava: TRACE
      hibernate:
        SQL: TRACE
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    com:
      netflix: INFO