# 修改端口号
server:
  port: 20006
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloud?useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: true
    generate-ddl: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  redis:
    # Redis默认是16个数据库，可以通过配置文件进行修改。
    # 每个数据库都有一个index来访问，没有名称！
    # 默认情况下，database的值是0~15。
    database: 1
    host: 127.0.0.1
    port: 6379

fk:
  short-messages:
    aliYun:
      # default或者cn-hangzhou
      region-id: cn-hangzhou
      # accessKeyId和secret是非常敏感的信息，可以在阿里云上面进行设置。
      # 在此设置的是一个测试账号，随时可能会被停止掉！
      access-key-id: LTAI4FmyL6BBqj6dx4NKSiMC
      secret: JlmgpxMkXwipB6PwW3lnhVQO5nGlcC
      # 阿里云短信API的版本
      version: 2017-05-25
      templates:
        verify-code:
          # 短信模板的ID
          id: SMS_148083316
          # 使用哪个短信签名
          sign-name: 疯狂软件
